"""Classify short acknowledgements and continuation utterances."""

from __future__ import annotations

from unicodedata import normalize as unicode_normalize


_NON_TOPIC_MAX_KEY_CHARS = 96

_ACKNOWLEDGEMENT_KEYS = frozenset({
    "ack",
    "acknowledged",
    "affirmative",
    "agreed",
    "allright",
    "alright",
    "confirmed",
    "correct",
    "exactly",
    "fine",
    "goahead",
    "gotit",
    "looksgood",
    "makesense",
    "muchappreciated",
    "noted",
    "ok",
    "okay",
    "received",
    "right",
    "roger",
    "soundsgood",
    "sure",
    "thankyou",
    "thanks",
    "understand",
    "understood",
    "willdo",
    "worksforme",
    "y",
    "yeah",
    "yep",
    "yes",
    "yup",
    "嗯",
    "嗯嗯",
    "哦",
    "喔",
    "好",
    "好啊",
    "好吧",
    "好哒",
    "好嘞",
    "好呀",
    "好的",
    "可以的",
    "了解",
    "了解了",
    "对",
    "对的",
    "对啊",
    "正是",
    "确实",
    "确实如此",
    "就这样",
    "就这么办",
    "懂了",
    "收到",
    "明白",
    "明白了",
    "是",
    "是的",
    "是啊",
    "是这样",
    "没毛病",
    "没问题",
    "没问题的",
    "没意见",
    "没错",
    "没错的",
    "妥",
    "妥了",
    "成",
    "成的",
    "可",
    "清楚了",
    "清楚",
    "照做",
    "照此办理",
    "知道了",
    "知悉",
    "知悉了",
    "记住了",
    "确认",
    "确定",
    "行",
    "行的",
    "赞同",
    "辛苦了",
    "谢谢",
    "同意",
    "认可",
    "可以",
    "按此执行",
    "按这个来",
    "就按这个来",
})

_NEGATIVE_ACKNOWLEDGEMENT_KEYS = frozenset({
    "cancel",
    "donot",
    "dont",
    "negative",
    "nevermind",
    "no",
    "nothanks",
    "nope",
    "not",
    "notnow",
    "notquite",
    "notreally",
    "pleasecancel",
    "pleasestop",
    "reject",
    "stop",
    "不",
    "不必",
    "不必了",
    "不对",
    "不同意",
    "不可以",
    "不是",
    "不要",
    "不要了",
    "不确认",
    "不行",
    "不需要",
    "不用",
    "不用了",
    "先不用",
    "暂时不用",
    "停止",
    "停下",
    "到此为止",
    "拒绝",
    "取消",
    "否",
    "否定",
    "没有",
    "算了",
    "算了吧",
    "别",
    "别了",
})

_CONTINUATION_KEYS = frozenset({
    "carryon",
    "continue",
    "continueplease",
    "doit",
    "execute",
    "goon",
    "keepgoing",
    "letuscontinue",
    "letscontinue",
    "moveon",
    "next",
    "nextone",
    "nextstep",
    "pickupwhereyouleftoff",
    "pleasecontinue",
    "pleasegoon",
    "pleaseproceed",
    "proceed",
    "resume",
    "resumeplease",
    "rerun",
    "runagain",
    "retry",
    "start",
    "then",
    "tryagain",
    "下一个",
    "下一项",
    "下一步",
    "开始",
    "开始吧",
    "开始执行",
    "再来",
    "再来一次",
    "再试",
    "再试一次",
    "再执行一次",
    "往下",
    "往下继续",
    "接着",
    "接着做",
    "接着来",
    "继续吧",
    "继续做",
    "继续完成",
    "继续进行",
    "继续下去",
    "然后呢",
    "继续",
    "继续处理",
    "继续执行",
    "请接着",
    "请继续",
    "重新执行",
    "重新开始",
    "重新试",
    "重试",
    "执行",
    "执行吧",
    "后续",
})

_POLITENESS_KEYS = frozenset({
    "kindly",
    "please",
    "thankyou",
    "thanks",
    "一下",
    "吧",
    "呀",
    "呢",
    "啦",
    "劳驾",
    "拜托",
    "请",
    "谢谢",
    "辛苦",
    "辛苦了",
    "麻烦",
})

_NON_TOPIC_COMPONENT_KEYS = tuple(sorted(
    (
        _ACKNOWLEDGEMENT_KEYS
        | _NEGATIVE_ACKNOWLEDGEMENT_KEYS
        | _CONTINUATION_KEYS
        | _POLITENESS_KEYS
    ),
    key=len,
    reverse=True,
))


def canonical_utterance_key(value: str) -> str:
    normalized = unicode_normalize("NFKC", value).casefold()
    return "".join(character for character in normalized if character.isalnum())


def is_non_topic_utterance(text: str) -> bool:
    """Return whether the complete short utterance contains no retrieval topic."""
    key = canonical_utterance_key(text)
    if not key or len(key) > _NON_TOPIC_MAX_KEY_CHARS:
        return False

    reachable = {0}
    for start in range(len(key)):
        if start not in reachable:
            continue
        for component in _NON_TOPIC_COMPONENT_KEYS:
            if key.startswith(component, start):
                reachable.add(start + len(component))
    return len(key) in reachable
