MAX_KNOWLEDGE_DOCUMENT_BYTES = 25 * 1024 * 1024
MAX_KNOWLEDGE_DOCUMENT_BATCH_SIZE = 50
MAX_KNOWLEDGE_FILENAME_BYTES = 255
SUPPORTED_KNOWLEDGE_DOCUMENT_SUFFIXES = frozenset({".md", ".pdf"})

KNOWLEDGE_GRAPH_EXPANSION_BATCH_SIZE = 100
KNOWLEDGE_GRAPH_MAX_NODES = 1000
