import json
import re
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

ROOT_PATH = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT_PATH / "web" / "openapi.json"
FRONTEND_CONTRACT_CONSTANTS_PATH = ROOT_PATH / "web" / "src" / "shared" / "api" / "generated" / "constants.ts"

if str(ROOT_PATH) not in sys.path:
    sys.path.insert(0, str(ROOT_PATH))

from app import create_app
from middleware.system_user import ACCESS_TOKEN_HEADER, require_admin, require_user
from pydantic import TypeAdapter
from schema.agent.events import (
    AgentEventTypeSchema,
    AgentEventSchema,
    AgentInputPartTypeSchema,
    DoneEvent,
    MAX_AGENT_IMAGES,
    MAX_AGENT_IMAGE_BYTES,
    MAX_AGENT_TOTAL_IMAGE_BYTES,
    RunStateEvent,
)
from schema.agent.sessions import AgentCode
from schema.agent.subordinates import AgentSubordinateTaskToolItem, AgentSubordinateTaskToolResult
from schema.common.tool_results import ReportToolResultOutputSchema, ToolResultSchema
from schema.deception.environments import (
    MAX_DECEPTION_REFERENCE_FILE_BYTES,
    MAX_DECEPTION_REFERENCE_FILES,
    MAX_DECEPTION_REFERENCE_TOTAL_BYTES,
    MAX_DECEPTION_REFERENCE_URL_LENGTH,
    MAX_DECEPTION_REFERENCE_URLS,
)
from schema.knowledge.resources import KNOWLEDGE_DOCUMENT_INFLIGHT_STATUSES
from schema.sandbox.command_outputs import (
    SandboxCommandOutputChunk,
    SandboxCommandResultMetadata,
)
from schema.threat.incidents import THREAT_INCIDENT_STATUS_TRANSITIONS
from service.common.pagination import RESOURCE_PAGE_SIZE
from service.knowledge.constants import (
    KNOWLEDGE_GRAPH_EXPANSION_BATCH_SIZE,
    KNOWLEDGE_GRAPH_MAX_NODES,
    SUPPORTED_KNOWLEDGE_DOCUMENT_SUFFIXES,
)


def export_openapi_schema() -> Path:
    app = create_app()
    schema = app.openapi()
    _patch_auth_contracts(app, schema)
    _patch_validation_contracts(schema)
    _patch_error_contracts(schema)
    _register_extra_schemas(schema)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        json.dumps(schema, ensure_ascii=False, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    export_frontend_contract_constants(schema)
    return OUTPUT_PATH


def export_frontend_contract_constants(schema: dict[str, Any]) -> Path:
    enum_constants = _enum_constants_ts(schema)
    config_constraints = _field_constraints(
        schema,
        (
            "AgentConfig",
            "AgentPoolConfig",
            "AgentRuntimeConfig",
            "BehaviorCaptureConfig",
            "ThreatAutomationConfig",
            "LightRAGConfig",
        ),
    )

    FRONTEND_CONTRACT_CONSTANTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    FRONTEND_CONTRACT_CONSTANTS_PATH.write_text(
        "// This file was auto-generated by scripts/export_schema.py.\n"
        "// Do not make direct changes to this file.\n\n"
        f"{enum_constants}\n\n"
        f"export const KNOWLEDGE_DOCUMENT_INFLIGHT_STATUS_VALUES = {json.dumps([status.value for status in KNOWLEDGE_DOCUMENT_INFLIGHT_STATUSES])} as const;\n"
        f"export const KNOWLEDGE_DOCUMENT_ACCEPT = {json.dumps(','.join(sorted(SUPPORTED_KNOWLEDGE_DOCUMENT_SUFFIXES)))};\n\n"
        f"export const RESOURCE_PAGE_SIZE = {RESOURCE_PAGE_SIZE};\n\n"
        f"export const MAX_AGENT_IMAGES = {MAX_AGENT_IMAGES};\n"
        f"export const MAX_AGENT_IMAGE_BYTES = {MAX_AGENT_IMAGE_BYTES};\n"
        f"export const MAX_AGENT_TOTAL_IMAGE_BYTES = {MAX_AGENT_TOTAL_IMAGE_BYTES};\n\n"
        f"export const MAX_DECEPTION_REFERENCE_FILES = {MAX_DECEPTION_REFERENCE_FILES};\n"
        f"export const MAX_DECEPTION_REFERENCE_FILE_BYTES = {MAX_DECEPTION_REFERENCE_FILE_BYTES};\n"
        f"export const MAX_DECEPTION_REFERENCE_TOTAL_BYTES = {MAX_DECEPTION_REFERENCE_TOTAL_BYTES};\n"
        f"export const MAX_DECEPTION_REFERENCE_URLS = {MAX_DECEPTION_REFERENCE_URLS};\n"
        f"export const MAX_DECEPTION_REFERENCE_URL_LENGTH = {MAX_DECEPTION_REFERENCE_URL_LENGTH};\n\n"
        f"export const SYSTEM_CONFIG_FIELD_CONSTRAINTS = {json.dumps(config_constraints)} as const;\n\n"
        f"export const THREAT_INCIDENT_STATUS_TRANSITIONS = {json.dumps({status.value: [next_status.value for next_status in transitions] for status, transitions in THREAT_INCIDENT_STATUS_TRANSITIONS.items()})} as const;\n\n"
        f"export const KNOWLEDGE_GRAPH_EXPANSION_BATCH_SIZE = {KNOWLEDGE_GRAPH_EXPANSION_BATCH_SIZE};\n"
        f"export const KNOWLEDGE_GRAPH_MAX_NODES = {KNOWLEDGE_GRAPH_MAX_NODES};\n\n"
        f"export const ACCESS_TOKEN_HEADER = {json.dumps(_get_access_token_header())};\n",
        encoding="utf-8",
    )
    return FRONTEND_CONTRACT_CONSTANTS_PATH


def _enum_constants_ts(schema: dict[str, Any]) -> str:
    schemas = schema.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict):
        raise RuntimeError("OpenAPI schema components are missing")

    exports: list[str] = []
    constant_sources: dict[str, str] = {}
    for schema_name, body in sorted(schemas.items()):
        if not isinstance(body, dict):
            continue
        values = body.get("enum")
        if not isinstance(values, list) or not values or not all(isinstance(value, str) and value for value in values):
            continue
        constant_name = _enum_constant_name(schema_name)
        previous = constant_sources.setdefault(constant_name, schema_name)
        if previous != schema_name:
            raise RuntimeError(
                f"OpenAPI enum constant collision: {previous} and {schema_name} both map to {constant_name}"
            )
        exports.extend((
            f"export const {constant_name}_VALUES = {json.dumps(values)} as const;",
            f"export const {constant_name} = {json.dumps(_enum_members(schema_name, values))} as const;",
        ))
    return "\n".join(exports)


def _enum_constant_name(schema_name: str) -> str:
    name = schema_name.removesuffix("Schema")
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def _enum_member_name(value: str) -> str:
    name = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
    return f"VALUE_{name}" if name[:1].isdigit() else name


def _enum_members(schema_name: str, values: list[str]) -> dict[str, str]:
    members: dict[str, str] = {}
    for value in values:
        member = _enum_member_name(value)
        previous = members.setdefault(member, value)
        if previous != value:
            raise RuntimeError(
                f"OpenAPI enum member collision in {schema_name}: {previous!r} and {value!r} both map to {member}"
            )
    return members


def _field_constraints(
    schema: dict[str, Any],
    schema_names: tuple[str, ...],
) -> dict[str, dict[str, dict[str, int | float]]]:
    schemas = schema.get("components", {}).get("schemas", {})
    constraint_names = (
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
        "minLength",
        "maxLength",
        "minItems",
        "maxItems",
    )
    result: dict[str, dict[str, dict[str, int | float]]] = {}
    for schema_name in schema_names:
        properties = schemas.get(schema_name, {}).get("properties")
        if not isinstance(properties, dict):
            raise RuntimeError(f"OpenAPI schema is missing properties for {schema_name}")
        result[schema_name] = {
            field_name: {
                constraint: _json_number(value)
                for constraint in constraint_names
                if isinstance((value := field_schema.get(constraint)), int | float)
            }
            for field_name, field_schema in properties.items()
            if isinstance(field_schema, dict)
            and any(isinstance(field_schema.get(constraint), int | float) for constraint in constraint_names)
        }
    return result


def _json_number(value: int | float) -> int | float:
    return int(value) if isinstance(value, float) and value.is_integer() else value


def _get_access_token_header() -> str:
    return ACCESS_TOKEN_HEADER


def _patch_auth_contracts(app: Any, schema: dict[str, Any]) -> None:
    """drive OpenAPI security from the FastAPI dependency tree.

    routes that depend on require_user get AccessTokenAuth + 401; routes that
    additionally depend on require_admin also get 403."""
    components = schema.setdefault("components", {})
    schemas = components.setdefault("schemas", {})
    schemas.setdefault("CommonResponse_Any_", _common_response_any_schema())
    components.setdefault("securitySchemes", {})["AccessTokenAuth"] = {
        "type": "apiKey",
        "in": "header",
        "name": _get_access_token_header(),
    }

    paths = schema.get("paths", {})
    for route in _iter_effective_routes(app):
        path = getattr(route, "path", "")
        methods = getattr(route, "methods", None)
        if not methods or path not in paths:
            continue

        deps = _route_dependency_funcs(route)
        if not (require_user in deps or require_admin in deps):
            continue

        for method in methods:
            operation = paths[path].get(method.lower())
            if operation is None:
                continue
            operation["security"] = [{"AccessTokenAuth": []}]
            responses = operation.setdefault("responses", {})
            responses["401"] = _common_response_ref("Unauthorized")
            if require_admin in deps:
                responses["403"] = _common_response_ref("Forbidden")


def _iter_effective_routes(app: Any) -> Iterator[Any]:
    for route in app.routes:
        contexts = getattr(route, "effective_route_contexts", None)
        if callable(contexts):
            yield from contexts()


def _route_dependency_funcs(route: Any) -> set:
    funcs: set = set()
    dependant = getattr(route, "dependant", None)
    if dependant is not None:
        _walk_dependant(dependant, funcs)
    return funcs


def _walk_dependant(dependant: Any, funcs: set) -> None:
    if dependant.call is not None:
        funcs.add(dependant.call)
    for sub in dependant.dependencies:
        _walk_dependant(sub, funcs)


def _patch_validation_contracts(schema: dict[str, Any]) -> None:
    """rewrite FastAPI's default 422 docs to the runtime CommonResponse shape"""
    for methods in schema.get("paths", {}).values():
        for operation in methods.values():
            responses = operation.get("responses")
            if isinstance(responses, dict) and "422" in responses:
                _ensure_common_response(responses["422"], "Validation Error")


def _patch_error_contracts(schema: dict[str, Any]) -> None:
    """normalize documented error responses to the runtime CommonResponse shape"""
    descriptions = {
        "400": "Bad Request",
        "401": "Unauthorized",
        "403": "Forbidden",
        "404": "Not Found",
        "422": "Validation Error",
    }
    for methods in schema.get("paths", {}).values():
        for operation in methods.values():
            responses = operation.get("responses")
            if not isinstance(responses, dict):
                continue
            for status_code, description in descriptions.items():
                response = responses.get(status_code)
                if isinstance(response, dict):
                    _ensure_common_response(response, description)


def _register_extra_schemas(schema: dict[str, Any]) -> None:
    """publish ws contracts as OpenAPI components so the frontend can derive types"""
    components = schema.setdefault("components", {})
    schemas = components.setdefault("schemas", {})

    extras = {
        "AgentEventTypeSchema": AgentEventTypeSchema,
        "AgentCode": AgentCode,
        "AgentInputPartTypeSchema": AgentInputPartTypeSchema,
        "DoneEvent": DoneEvent,
        "RunStateEvent": RunStateEvent,
        "AgentEventSchema": AgentEventSchema,
        "AgentSubordinateTaskToolItem": AgentSubordinateTaskToolItem,
        "AgentSubordinateTaskToolResult": AgentSubordinateTaskToolResult,
        "ToolResultSchema": ToolResultSchema,
        "ReportToolResultOutputSchema": ReportToolResultOutputSchema,
        "SandboxCommandResultMetadata": SandboxCommandResultMetadata,
        "SandboxCommandOutputChunk": SandboxCommandOutputChunk,
    }
    for name, model in extras.items():
        body = TypeAdapter(model).json_schema(ref_template="#/components/schemas/{model}")
        for nested_name, nested_body in body.pop("$defs", {}).items():
            schemas.setdefault(nested_name, nested_body)
        schemas[name] = body


def _common_response_ref(description: str) -> dict[str, Any]:
    return {
        "description": description,
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/CommonResponse_Any_"},
            },
        },
    }


def _ensure_common_response(response: dict[str, Any], description: str) -> None:
    response["description"] = response.get("description") or description
    content = response.setdefault("content", {})
    json_content = content.setdefault("application/json", {})
    json_content["schema"] = {"$ref": "#/components/schemas/CommonResponse_Any_"}


def _common_response_any_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "title": "CommonResponse[Any]",
        "properties": {
            "code": {"type": "integer", "title": "Code", "default": 200},
            "message": {"type": "string", "title": "Message", "default": "success"},
            "data": {"title": "Data"},
        },
    }


def main() -> None:
    output_path = export_openapi_schema()
    print(f"OpenAPI schema exported to {output_path}")
    print(f"Frontend contract constants exported to {FRONTEND_CONTRACT_CONSTANTS_PATH}")


if __name__ == "__main__":
    main()
